language: python
python:
    # We don't actually use the Travis Python, but this keeps it organized.
    - '2.6'
    - '2.7'
    - '3.3'
    - '3.4'
install:
    - sudo apt-get update
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda

    # Useful for debugging any issues with conda.
    - conda info -a

    # Create conda environment and install dependencies.
    - conda create -q -n test python=$TRAVIS_PYTHON_VERSION numpy pandas matplotlib seaborn pytest
    - source activate test
    - pip install pysam

script: py.test